export const RARITIES = ['♢','♢♢','♢♢♢','♢♢♢♢','☆','☆☆','☆☆☆','♛'];

export const PACK_RATES = [0.99950, 0.00050]; 

export const DRAW_RATES = {
    regular: [ 
        [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.9, 0.05, 0.01666, 0.02572, 0.00500, 0.00222, 0.00040],
        [0.0, 0.6, 0.2, 0.06664, 0.10288, 0.02000, 0.00888, 0.00160]
    ],
    rare: [ 
        [0.0, 0.0, 0.0, 0.0, 0.4, 0.5, 0.05, 0.05],
        [0.0, 0.0, 0.0, 0.0, 0.4, 0.5, 0.05, 0.05],
        [0.0, 0.0, 0.0, 0.0, 0.4, 0.5, 0.05, 0.05],
        [0.0, 0.0, 0.0, 0.0, 0.4, 0.5, 0.05, 0.05],
        [0.0, 0.0, 0.0, 0.0, 0.4, 0.5, 0.05, 0.05]
    ]
};

export const CARD_LIST = [
    {"id": "A1 001", "name-en": "Bulbasaur", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "奇異種子"},
    {"id": "A1 002", "name-en": "Ivysaur", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "奇異草"},
    {"id": "A1 003", "name-en": "Venusaur", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "奇異花"},
    {"id": "A1 004", "name-en": "Venusaur ex", "pack": "Mewtwo", "rarity": "♢♢♢♢", "name-zhhk": "奇異花 ex"},
    {"id": "A1 005", "name-en": "Caterpie", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "綠毛蟲"},
    {"id": "A1 006", "name-en": "Metapod", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "鐵甲蟲"},
    {"id": "A1 007", "name-en": "Butterfree", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "巴他蝶"},
    {"id": "A1 008", "name-en": "Weedle", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "獨角蟲"},
    {"id": "A1 009", "name-en": "Kakuna", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "鐵殼蛹"},
    {"id": "A1 010", "name-en": "Beedrill", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "大針蜂"},
    {"id": "A1 011", "name-en": "Oddish", "pack": "Charizard", "rarity": "♢", "name-zhhk": "臭臭花"},
    {"id": "A1 012", "name-en": "Gloom", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "臭臭花"},
    {"id": "A1 013", "name-en": "Vileplume", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "臭臭花"},
    {"id": "A1 014", "name-en": "Paras", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "綠毛蟲"},
    {"id": "A1 015", "name-en": "Parasect", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "綠毛蟲"},
    {"id": "A1 016", "name-en": "Venonat", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "綠毛蟲"},
    {"id": "A1 017", "name-en": "Venomoth", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "巴他蝶"},
    {"id": "A1 018", "name-en": "Bellsprout", "pack": "Charizard", "rarity": "♢", "name-zhhk": "喇叭芽"},
    {"id": "A1 019", "name-en": "Weepinbell", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "喇叭芽"},
    {"id": "A1 020", "name-en": "Victreebel", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "喇叭芽"},
    {"id": "A1 021", "name-en": "Exeggcute", "pack": "Charizard", "rarity": "♢", "name-zhhk": "奇異種子"},
    {"id": "A1 022", "name-en": "Exeggutor", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "奇異種子"},
    {"id": "A1 023", "name-en": "Exeggutor ex", "pack": "Charizard", "rarity": "♢♢♢♢", "name-zhhk": "奇異種子 ex"},
    {"id": "A1 024", "name-en": "Tangela", "pack": "Charizard", "rarity": "♢", "name-zhhk": "龍葉草"},
    {"id": "A1 025", "name-en": "Scyther", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "飛天螳螂"},
    {"id": "A1 026", "name-en": "Pinsir", "pack": "All", "rarity": "♢♢", "name-zhhk": "大鉗蟹"},
    {"id": "A1 027", "name-en": "Cottonee", "pack": "All", "rarity": "♢", "name-zhhk": "棉棉"},
    {"id": "A1 028", "name-en": "Whimsicott", "pack": "All", "rarity": "♢♢", "name-zhhk": "棉棉"},
    {"id": "A1 029", "name-en": "Petilil", "pack": "All", "rarity": "♢", "name-zhhk": "小草"},
    {"id": "A1 030", "name-en": "Lilligant", "pack": "All", "rarity": "♢♢", "name-zhhk": "大花"},
    {"id": "A1 031", "name-en": "Skiddo", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小木"},
    {"id": "A1 032", "name-en": "Gogoat", "pack": "Charizard", "rarity": "♢", "name-zhhk": "大木"},
    {"id": "A1 033", "name-en": "Charmander", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小火龍"},
    {"id": "A1 034", "name-en": "Charmeleon", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "火恐龍"},
    {"id": "A1 035", "name-en": "Charizard", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "火恐龍"},
    {"id": "A1 036", "name-en": "Charizard ex", "pack": "Charizard", "rarity": "♢♢♢♢", "name-zhhk": "火恐龍 ex"},
    {"id": "A1 037", "name-en": "Vulpix", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小狐"},
    {"id": "A1 038", "name-en": "Ninetales", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "九尾"},
    {"id": "A1 039", "name-en": "Growlithe", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "火犬"},
    {"id": "A1 040", "name-en": "Arcanine", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "火犬"},
    {"id": "A1 041", "name-en": "Arcanine ex", "pack": "Pikachu", "rarity": "♢♢♢♢", "name-zhhk": "火犬 ex"},
    {"id": "A1 042", "name-en": "Ponyta", "pack": "All", "rarity": "♢", "name-zhhk": "小火馬"},
    {"id": "A1 043", "name-en": "Rapidash", "pack": "All", "rarity": "♢♢", "name-zhhk": "快跑"},
    {"id": "A1 044", "name-en": "Magmar", "pack": "Charizard", "rarity": "♢", "name-zhhk": "火馬"},
    {"id": "A1 045", "name-en": "Flareon", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "火恐龍"},
    {"id": "A1 046", "name-en": "Moltres", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "火鳥"},
    {"id": "A1 047", "name-en": "Moltres ex", "pack": "Charizard", "rarity": "♢♢♢♢", "name-zhhk": "火鳥 ex"},
    {"id": "A1 048", "name-en": "Heatmor", "pack": "All", "rarity": "♢", "name-zhhk": "火頭"},
    {"id": "A1 049", "name-en": "Salandit", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "火頭"},
    {"id": "A1 050", "name-en": "Salazzle", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "火頭"},
    {"id": "A1 051", "name-en": "Sizzlipede", "pack": "All", "rarity": "♢", "name-zhhk": "火蟲"},
    {"id": "A1 052", "name-en": "Centiskorch", "pack": "All", "rarity": "♢♢", "name-zhhk": "火蟲"},
    {"id": "A1 053", "name-en": "Squirtle", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "水龜"},
    {"id": "A1 054", "name-en": "Wartortle", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "水龜"},
    {"id": "A1 055", "name-en": "Blastoise", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "水炮"},
    {"id": "A1 056", "name-en": "Blastoise ex", "pack": "Pikachu", "rarity": "♢♢♢♢", "name-zhhk": "水炮 ex"},
    {"id": "A1 057", "name-en": "Psyduck", "pack": "All", "rarity": "♢", "name-zhhk": "水鼠"},
    {"id": "A1 058", "name-en": "Golduck", "pack": "All", "rarity": "♢♢", "name-zhhk": "水鼠"},
    {"id": "A1 059", "name-en": "Poliwag", "pack": "Charizard", "rarity": "♢", "name-zhhk": "水蛙"},
    {"id": "A1 060", "name-en": "Poliwhirl", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "水蛙"},
    {"id": "A1 061", "name-en": "Poliwrath", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "水蛙"},
    {"id": "A1 062", "name-en": "Tentacool", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "水母"},
    {"id": "A1 063", "name-en": "Tentacruel", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "水母"},
    {"id": "A1 064", "name-en": "Seel", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "海豹"},
    {"id": "A1 065", "name-en": "Dewgong", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "海豹"},
    {"id": "A1 066", "name-en": "Shellder", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "海貝"},
    {"id": "A1 067", "name-en": "Cloyster", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "海貝"},
    {"id": "A1 068", "name-en": "Krabby", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "小海蟹"},
    {"id": "A1 069", "name-en": "Kingler", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "大鉗蟹"},
    {"id": "A1 070", "name-en": "Horsea", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小海馬"},
    {"id": "A1 071", "name-en": "Seadra", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "海馬"},
    {"id": "A1 072", "name-en": "Goldeen", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小金魚"},
    {"id": "A1 073", "name-en": "Seaking", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "大金魚"},
    {"id": "A1 074", "name-en": "Staryu", "pack": "Charizard", "rarity": "♢", "name-zhhk": "星魚"},
    {"id": "A1 075", "name-en": "Starmie", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "星魚"},
    {"id": "A1 076", "name-en": "Starmie ex", "pack": "Charizard", "rarity": "♢♢♢♢", "name-zhhk": "星魚 ex"},
    {"id": "A1 077", "name-en": "Magikarp", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小鯉魚"},
    {"id": "A1 078", "name-en": "Gyarados", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "鯉魚"},
    {"id": "A1 079", "name-en": "Lapras", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "拉普拉斯"},
    {"id": "A1 080", "name-en": "Vaporeon", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "水伊貝"},
    {"id": "A1 081", "name-en": "Omanyte", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "多刺菊石"},
    {"id": "A1 082", "name-en": "Omastar", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "多刺菊石"},
    {"id": "A1 083", "name-en": "Articuno", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "冰伊貝"},
    {"id": "A1 084", "name-en": "Articuno ex", "pack": "Mewtwo", "rarity": "♢♢♢♢", "name-zhhk": "冰伊貝 ex"},
    {"id": "A1 085", "name-en": "Ducklett", "pack": "Charizard", "rarity": "♢", "name-zhhk": "鴨嘴"},
    {"id": "A1 086", "name-en": "Swanna", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "天鵝"},
    {"id": "A1 087", "name-en": "Froakie", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小蝌蚪"},
    {"id": "A1 088", "name-en": "Frogadier", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "蝌蚪"},
    {"id": "A1 089", "name-en": "Greninja", "pack": "Charizard", "rarity": "♢", "name-zhhk": "水忍者"},
    {"id": "A1 090", "name-en": "Pyukumuku", "pack": "Charizard", "rarity": "♢", "name-zhhk": "水球"},
    {"id": "A1 091", "name-en": "Bruxish", "pack": "All", "rarity": "♢♢", "name-zhhk": "水魚"},
    {"id": "A1 092", "name-en": "Snom", "pack": "All", "rarity": "♢", "name-zhhk": "雪球"},
    {"id": "A1 093", "name-en": "Frosmoth", "pack": "All", "rarity": "♢♢", "name-zhhk": "雪球"},
    {"id": "A1 094", "name-en": "Pikachu", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "皮卡丘"},
    {"id": "A1 095", "name-en": "Raichu", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "雷丘"},
    {"id": "A1 096", "name-en": "Pikachu ex", "pack": "Pikachu", "rarity": "♢♢♢♢", "name-zhhk": "皮卡 ex"},
    {"id": "A1 097", "name-en": "Magnemite", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "磁石"},
    {"id": "A1 098", "name-en": "Magneton", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "磁石"},
    {"id": "A1 099", "name-en": "Voltorb", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "電球"},
    {"id": "A1 100", "name-en": "Electrode", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "電擊怪"},
    {"id": "A1 101", "name-en": "Electabuzz", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "擊獸"},
    {"id": "A1 102", "name-en": "Jolteon", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "電擊獸"},
    {"id": "A1 103", "name-en": "Zapdos", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "電擊獸"},
    {"id": "A1 104", "name-en": "Zapdos ex", "pack": "Pikachu", "rarity": "♢♢♢♢", "name-zhhk": "電擊獸 ex"},
    {"id": "A1 105", "name-en": "Blitzle", "pack": "All", "rarity": "♢", "name-zhhk": "閃電"},
    {"id": "A1 106", "name-en": "Zebstrika", "pack": "All", "rarity": "♢♢", "name-zhhk": "閃電"},
    {"id": "A1 107", "name-en": "Tynamo", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "小電"},
    {"id": "A1 108", "name-en": "Eelektrik", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "小電"},
    {"id": "A1 109", "name-en": "Eelektross", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "大電"},
    {"id": "A1 110", "name-en": "Helioptile", "pack": "All", "rarity": "♢", "name-zhhk": "小太陽"},
    {"id": "A1 111", "name-en": "Heliolisk", "pack": "All", "rarity": "♢", "name-zhhk": "大太陽"},
    {"id": "A1 112", "name-en": "Pincurchin", "pack": "All", "rarity": "♢♢", "name-zhhk": "小鋸"},
    {"id": "A1 113", "name-en": "Clefairy", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小仙女"},
    {"id": "A1 114", "name-en": "Clefable", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "大仙女"},
    {"id": "A1 115", "name-en": "Abra", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小鬼"},
    {"id": "A1 116", "name-en": "Kadabra", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "大鬼"},
    {"id": "A1 117", "name-en": "Alakazam", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "大鬼"},
    {"id": "A1 118", "name-en": "Slowpoke", "pack": "All", "rarity": "♢", "name-zhhk": "慢吞吞"},
    {"id": "A1 119", "name-en": "Slowbro", "pack": "All", "rarity": "♢♢", "name-zhhk": "慢吞吞"},
    {"id": "A1 120", "name-en": "Gastly", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "鬼斯"},
    {"id": "A1 121", "name-en": "Haunter", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "鬼斯"},
    {"id": "A1 122", "name-en": "Gengar", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "鬼斯"},
    {"id": "A1 123", "name-en": "Gengar ex", "pack": "Mewtwo", "rarity": "♢♢♢♢", "name-zhhk": "鬼斯 ex"},
    {"id": "A1 124", "name-en": "Drowzee", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "夢妖"},
    {"id": "A1 125", "name-en": "Hypno", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "夢妖"},
    {"id": "A1 126", "name-en": "Mr. Mime", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "模仿"},
    {"id": "A1 127", "name-en": "Jynx", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "冰精"},
    {"id": "A1 128", "name-en": "Mewtwo", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "超夢"},
    {"id": "A1 129", "name-en": "Mewtwo ex", "pack": "Mewtwo", "rarity": "♢♢♢♢", "name-zhhk": "超夢夢 ex"},
    {"id": "A1 130", "name-en": "Ralts", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "拉魯拉斯"},
    {"id": "A1 131", "name-en": "Kirlia", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "奇魯莉安"},
    {"id": "A1 132", "name-en": "Gardevoir", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "奇魯莉安"},
    {"id": "A1 133", "name-en": "Woobat", "pack": "All", "rarity": "♢", "name-zhhk": "小蝙蝠"},
    {"id": "A1 134", "name-en": "Swoobat", "pack": "All", "rarity": "♢", "name-zhhk": "大蝙蝠"},
    {"id": "A1 135", "name-en": "Golett", "pack": "All", "rarity": "♢", "name-zhhk": "小鋸"},
    {"id": "A1 136", "name-en": "Golurk", "pack": "All", "rarity": "♢♢", "name-zhhk": "大鋸"},
    {"id": "A1 137", "name-en": "Sandshrew", "pack": "All", "rarity": "♢", "name-zhhk": "沙鈍"},
    {"id": "A1 138", "name-en": "Sandslash", "pack": "All", "rarity": "♢♢", "name-zhhk": "沙鈍"},
    {"id": "A1 139", "name-en": "Diglett", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "地鼠"},
    {"id": "A1 140", "name-en": "Dugtrio", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "地鼠"},
    {"id": "A1 141", "name-en": "Mankey", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小拳石"},
    {"id": "A1 142", "name-en": "Primeape", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "大拳石"},
    {"id": "A1 143", "name-en": "Machop", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小拳"},
    {"id": "A1 144", "name-en": "Machoke", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "大拳"},
    {"id": "A1 145", "name-en": "Machamp", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "大拳"},
    {"id": "A1 146", "name-en": "Machamp ex", "pack": "Charizard", "rarity": "♢♢♢♢", "name-zhhk": "大拳 ex"},
    {"id": "A1 147", "name-en": "Geodude", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小岩"},
    {"id": "A1 148", "name-en": "Graveler", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "大岩"},
    {"id": "A1 149", "name-en": "Golem", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "大岩"},
    {"id": "A1 150", "name-en": "Onix", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "蛇紋石"},
    {"id": "A1 151", "name-en": "Cubone", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "小骨"},
    {"id": "A1 152", "name-en": "Marowak", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "大骨"},
    {"id": "A1 153", "name-en": "Marowak ex", "pack": "Mewtwo", "rarity": "♢♢♢♢", "name-zhhk": "大骨 ex"},
    {"id": "A1 154", "name-en": "Hitmonlee", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "拳擊"},
    {"id": "A1 155", "name-en": "Hitmonchan", "pack": "Charizard", "rarity": "♢", "name-zhhk": "拳擊"},
    {"id": "A1 156", "name-en": "Rhyhorn", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "鐵角"},
    {"id": "A1 157", "name-en": "Rhydon", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "鐵角"},
    {"id": "A1 158", "name-en": "Kabuto", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "鈍"},
    {"id": "A1 159", "name-en": "Kabutops", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "鈍"},
    {"id": "A1 160", "name-en": "Mienfoo", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小貓"},
    {"id": "A1 161", "name-en": "Mienshao", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "大貓"},
    {"id": "A1 162", "name-en": "Clobbopus", "pack": "All", "rarity": "♢", "name-zhhk": "小拳"},
    {"id": "A1 163", "name-en": "Grapploct", "pack": "All", "rarity": "♢♢", "name-zhhk": "大拳"},
    {"id": "A1 164", "name-en": "Ekans", "pack": "All", "rarity": "♢", "name-zhhk": "小蛇"},
    {"id": "A1 165", "name-en": "Arbok", "pack": "All", "rarity": "♢♢", "name-zhhk": "大蛇"},
    {"id": "A1 166", "name-en": "Nidoran♀", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小雌"},
    {"id": "A1 167", "name-en": "Nidorina", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "雌"},
    {"id": "A1 168", "name-en": "Nidoqueen", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "雌"},
    {"id": "A1 169", "name-en": "Nidoran♂", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小雄"},
    {"id": "A1 170", "name-en": "Nidorino", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "雄"},
    {"id": "A1 171", "name-en": "Nidoking", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "雄"},
    {"id": "A1 172", "name-en": "Zubat", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "蝙"},
    {"id": "A1 173", "name-en": "Golbat", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "蝙蝠"},
    {"id": "A1 174", "name-en": "Grimer", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "臭臭"},
    {"id": "A1 175", "name-en": "Muk", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "臭臭"},
    {"id": "A1 176", "name-en": "Koffing", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "臭臭"},
    {"id": "A1 177", "name-en": "Weezing", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "臭臭"},
    {"id": "A1 178", "name-en": "Mawile", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小貓"},
    {"id": "A1 179", "name-en": "Pawniard", "pack": "All", "rarity": "♢", "name-zhhk": "小劍"},
    {"id": "A1 180", "name-en": "Bisharp", "pack": "All", "rarity": "♢♢", "name-zhhk": "大劍"},
    {"id": "A1 181", "name-en": "Meltan", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小鐵"},
    {"id": "A1 182", "name-en": "Melmetal", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "大鐵"},
    {"id": "A1 183", "name-en": "Dratini", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "小龍"},
    {"id": "A1 184", "name-en": "Dragonair", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "龍"},
    {"id": "A1 185", "name-en": "Dragonite", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "龍"},
    {"id": "A1 186", "name-en": "Pidgey", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "小鳥"},
    {"id": "A1 187", "name-en": "Pidgeotto", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "鳥"},
    {"id": "A1 188", "name-en": "Pidgeot", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "鳥"},
    {"id": "A1 189", "name-en": "Rattata", "pack": "All", "rarity": "♢", "name-zhhk": "小鼠"},
    {"id": "A1 190", "name-en": "Raticate", "pack": "All", "rarity": "♢", "name-zhhk": "鼠"},
    {"id": "A1 191", "name-en": "Spearow", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小鳥"},
    {"id": "A1 192", "name-en": "Fearow", "pack": "Charizard", "rarity": "♢", "name-zhhk": "鳥"},
    {"id": "A1 193", "name-en": "Jigglypuff", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小胖丁"},
    {"id": "A1 194", "name-en": "Wigglytuff", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "胖丁"},
    {"id": "A1 195", "name-en": "Wigglytuff ex", "pack": "Pikachu", "rarity": "♢♢♢♢", "name-zhhk": "胖丁 ex"},
    {"id": "A1 196", "name-en": "Meowth", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小貓"},
    {"id": "A1 197", "name-en": "Persian", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "貓"},
    {"id": "A1 198", "name-en": "Farfetch'd", "pack": "All", "rarity": "♢", "name-zhhk": "小鴨"},
    {"id": "A1 199", "name-en": "Doduo", "pack": "All", "rarity": "♢", "name-zhhk": "小鴨"},
    {"id": "A1 200", "name-en": "Dodrio", "pack": "All", "rarity": "♢♢", "name-zhhk": "大鴨"},
    {"id": "A1 201", "name-en": "Lickitung", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "舌頭"},
    {"id": "A1 202", "name-en": "Chansey", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "蛋"},
    {"id": "A1 203", "name-en": "Kangaskhan", "pack": "Charizard", "rarity": "♢♢♢", "name-zhhk": "袋龍"},
    {"id": "A1 204", "name-en": "Tauros", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "牛"},
    {"id": "A1 205", "name-en": "Ditto", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "變變"},
    {"id": "A1 206", "name-en": "Eevee", "pack": "Charizard", "rarity": "♢", "name-zhhk": "小伊貝"},
    {"id": "A1 207", "name-en": "Eevee", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "小伊貝"},
    {"id": "A1 208", "name-en": "Eevee", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "小伊貝"},
    {"id": "A1 209", "name-en": "Porygon", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "波波"},
    {"id": "A1 210", "name-en": "Aerodactyl", "pack": "Mewtwo", "rarity": "♢♢♢", "name-zhhk": "翼龍"},
    {"id": "A1 211", "name-en": "Snorlax", "pack": "Pikachu", "rarity": "♢♢♢", "name-zhhk": "懶人"},
    {"id": "A1 212", "name-en": "Minccino", "pack": "All", "rarity": "♢", "name-zhhk": "小貓"},
    {"id": "A1 213", "name-en": "Cinccino", "pack": "All", "rarity": "♢♢", "name-zhhk": "大貓"},
    {"id": "A1 214", "name-en": "Wooloo", "pack": "All", "rarity": "♢", "name-zhhk": "小羊"},
    {"id": "A1 215", "name-en": "Dubwool", "pack": "All", "rarity": "♢", "name-zhhk": "大羊"},
    {"id": "A1 216", "name-en": "Helix Fossil", "pack": "Pikachu", "rarity": "♢", "name-zhhk": "螺"},
    {"id": "A1 217", "name-en": "Dome Fossil", "pack": "Charizard", "rarity": "♢", "name-zhhk": "殼"},
    {"id": "A1 218", "name-en": "Old Amber", "pack": "Mewtwo", "rarity": "♢", "name-zhhk": "琥珀"},
    {"id": "A1 219", "name-en": "Erika", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "艾莉卡"},
    {"id": "A1 220", "name-en": "Misty", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "水"},
    {"id": "A1 221", "name-en": "Blaine", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "布萊恩"},
    {"id": "A1 222", "name-en": "Koga", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "古加"},
    {"id": "A1 223", "name-en": "Giovanni", "pack": "Mewtwo", "rarity": "♢♢", "name-zhhk": "喬伊"},
    {"id": "A1 224", "name-en": "Brock", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "布洛"},
    {"id": "A1 225", "name-en": "Sabrina", "pack": "Charizard", "rarity": "♢♢", "name-zhhk": "莎莉娜"},
    {"id": "A1 226", "name-en": "Lt. Surge", "pack": "Pikachu", "rarity": "♢♢", "name-zhhk": "局長"},
    {"id": "A1 227", "name-en": "Bulbasaur", "pack": "Mewtwo", "rarity": "", "name-zhhk": "奇異種子"},
    {"id": "A1 228", "name-en": "Gloom", "pack": "Charizard", "rarity": "☆", "name-zhhk": "臭臭花"},
    {"id": "A1 229", "name-en": "Pinsir", "pack": "Charizard", "rarity": "☆", "name-zhhk": "大鉗蟹"},
    {"id": "A1 230", "name-en": "Charmander", "pack": "Charizard", "rarity": "☆", "name-zhhk": "小火龍"},
    {"id": "A1 231", "name-en": "Rapidash", "pack": "Charizard", "rarity": "☆", "name-zhhk": "烈焰馬"},
    {"id": "A1 232", "name-en": "Squirtle", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "水"},
    {"id": "A1 233", "name-en": "Gyarados", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "鯉魚"},
    {"id": "A1 234", "name-en": "Lapras", "pack": "Charizard", "rarity": "☆", "name-zhhk": "拉普拉"},
    {"id": "A1 235", "name-en": "Electrode", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "電擊怪"},
    {"id": "A1 236", "name-en": "Alakazam", "pack": "Charizard", "rarity": "☆", "name-zhhk": "大鬼"},
    {"id": "A1 237", "name-en": "Slowpoke", "pack": "Charizard", "rarity": "☆", "name-zhhk": "慢吞吞"},
    {"id": "A1 238", "name-en": "Diglett", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "地鼠"},
    {"id": "A1 239", "name-en": "Cubone", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "小骨"},
    {"id": "A1 240", "name-en": "Nidoqueen", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "雌"},
    {"id": "A1 241", "name-en": "Nidoking", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "雄"},
    {"id": "A1 242", "name-en": "Golbat", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "蝙蝠"},
    {"id": "A1 243", "name-en": "Weezing", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "臭臭"},
    {"id": "A1 244", "name-en": "Dragonite", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "龍"},
    {"id": "A1 245", "name-en": "Pidgeot", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "鳥"},
    {"id": "A1 246", "name-en": "Meowth", "pack": "Charizard", "rarity": "☆", "name-zhhk": "小貓"},
    {"id": "A1 247", "name-en": "Ditto", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "變變"},
    {"id": "A1 248", "name-en": "Eevee", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "小伊貝"},
    {"id": "A1 249", "name-en": "Porygon", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "波波"},
    {"id": "A1 250", "name-en": "Snorlax", "pack": "Pikachu", "rarity": "☆", "name-zhhk": "人"},
    {"id": "A1 251", "name-en": "Venusaur ex", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "奇異花 ex"},
    {"id": "A1 252", "name-en": "Exeggutor ex", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "奇異種子 ex"},
    {"id": "A1 253", "name-en": "Charizard ex", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "火恐龍 ex"},
    {"id": "A1 254", "name-en": "Arcanine ex", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "火犬"},
    {"id": "A1 255", "name-en": "Moltres ex", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "火鳥 ex"},
    {"id": "A1 256", "name-en": "Blastoise ex", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "水炮 ex"},
    {"id": "A1 257", "name-en": "Starmie ex", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "星魚"},
    {"id": "A1 258", "name-en": "Articuno ex", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "冰伊貝 ex"},
    {"id": "A1 259", "name-en": "Pikachu ex", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "皮卡丘 ex"},
    {"id": "A1 260", "name-en": "Zapdos ex", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "電擊獸 ex"},
    {"id": "A1 261", "name-en": "Gengar ex", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "鬼斯 ex"},
    {"id": "A1 262", "name-en": "Mewtwo ex", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "超夢夢 ex"},
    {"id": "A1 263", "name-en": "Machamp ex", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "怪力 ex"},
    {"id": "A1 264", "name-en": "Marowak ex", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "格拉格拉	 ex"},
    {"id": "A1 265", "name-en": "Wigglytuff ex", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "肥波球 ex"},
    {"id": "A1 266", "name-en": "Erika", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "艾莉卡"},
    {"id": "A1 267", "name-en": "Misty", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "水"},
    {"id": "A1 268", "name-en": "Blaine", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "布萊恩"},
    {"id": "A1 269", "name-en": "Koga", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "古加"},
    {"id": "A1 270", "name-en": "Giovanni", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "喬伊"},
    {"id": "A1 271", "name-en": "Brock", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "布洛"},
    {"id": "A1 272", "name-en": "Sabrina", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "莎莉娜"},
    {"id": "A1 273", "name-en": "Lt. Surge", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "局長"},
    {"id": "A1 274", "name-en": "Moltres ex", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "火鳥 ex"},
    {"id": "A1 275", "name-en": "Articuno ex", "pack": "Mewtwo", "rarity": "☆", "name-zhhk": "冰伊貝 ex"},
    {"id": "A1 276", "name-en": "Zapdos ex", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "電擊獸 ex"},
    {"id": "A1 277", "name-en": "Gengar ex", "pack": "Mewtwo", "rarity": "☆☆", "name-zhhk": "鬼斯 ex"},
    {"id": "A1 278", "name-en": "Machamp ex", "pack": "Charizard", "rarity": "☆☆", "name-zhhk": "怪力 ex"},
    {"id": "A1 279", "name-en": "Wigglytuff ex", "pack": "Pikachu", "rarity": "☆☆", "name-zhhk": "肥波球 ex"},
    {"id": "A1 280", "name-en": "Charizard ex", "pack": "Charizard", "rarity": "☆☆☆", "name-zhhk": "火恐龍 ex"},
    {"id": "A1 281", "name-en": "Pikachu ex", "pack": "Pikachu", "rarity": "☆☆☆", "name-zhhk": "比卡超 ex"},
    {"id": "A1 282", "name-en": "Mewtwo ex", "pack": "Mewtwo", "rarity": "☆☆☆", "name-zhhk": "超夢夢 ex"},
    {"id": "A1 283", "name-en": "Mew", "pack": "Unlocked", "rarity": "", "name-zhhk": "夢夢"},
    {"id": "A1 284", "name-en": "Charizard ex", "pack": "All", "rarity": "♛", "name-zhhk": "噴火龍 ex"},
    {"id": "A1 285", "name-en": "Pikachu ex", "pack": "All", "rarity": "♛", "name-zhhk": "比卡超 ex"},
    {"id": "A1 286", "name-en": "Mewtwo ex", "pack": "All", "rarity": "♛", "name-zhhk": "超夢夢 ex"}
];